// Hand-written types for the CJS Babel locator plugin shipped at
// `@thientran01/muse/babel` (dist/muse-loc.cjs). It's a Babel plugin factory —
// used as `plugins: [museLoc]` in a Vite react() babel config or a babel-loader
// rule. muse-loc.cjs is plain JSDoc-typed JS, so this twin is copied into dist
// by copyBabel.mjs rather than generated by tsup.
declare function museLoc(babel: { types: unknown }): {
  name?: string
  visitor: Record<string, unknown>
}

export default museLoc
export { museLoc }
